@ECHO OFF
SETLOCAL ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION
SET VCPKG_DIR=D:\Source\Repos\darktxt\meGB\vcpkg
SET VISUAL_STUDIO_VERSION="Visual Studio 16 2019"
SET VSCMD_ARG_TGT_ARCH=x64

RMDIR /s/q build
MKDIR build
PUSHD build

%VCPKG_DIR%\vcpkg.exe install sdl2:%VSCMD_ARG_TGT_ARCH%-windows
%VCPKG_DIR%\vcpkg.exe install gtest:%VSCMD_ARG_TGT_ARCH%-windows

cmake .. "-DCMAKE_TOOLCHAIN_FILE=%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=%VSCMD_ARG_TGT_ARCH%-windows -G %VISUAL_STUDIO_VERSION%

ENDLOCAL
